server:
  port: 8085

spring:
  application:
    name: claim-service
  datasource:
    url: jdbc:postgresql://localhost:5432/autoClaimClaim
    username: postgres
    password: p1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

gemini:
  api:
    key: MYGEMİNİAPİKEY