server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # 1. Identity Service
            - id: identity-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            # 2. Claim Service
            - id: claim-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/claims/**

            # 3. Pricing Service
            - id: pricing-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/prices/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG